### ISSUE TITLE
Remove completed bombs

### ISSUE THREAD

**Issue by ashbash1987** [ashbash1987/ktanemod-factory#35]
'Infinite' modes are not really infinite at the moment, since all the old bombs still exist in the gameplay room, meaning eventually the game will come to a stop either from lack of memory availability or just sheer amount of GameObject's to process.

There appears to be a command to allow deleting of bombs from the gameplay room in a safer manner than just manually destroying it.

**Comment by CaitSith2** [comment]
The command is SceneManager.Instance.GameplayState.RemoveBomb(<bomb>);

The key, is that <bomb> must be Solved, before the game will destroy it.  Also, if <bomb> is the first bomb in SceneManager.Instance.GameplayState.Bombs,  the game will Just Set that bomb inactive, rather than remove it from the list and destroy it.
